name: Main
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v3

      - name: Read .nvmrc for Node.js version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nvm.outputs.NODE_VERSION }}'

      - name: Install dependencies
        run: npm ci

      - name: Prettier
        run: npm run prettier:check

      - name: ESLint
        run: npm run eslint:check

      - name: Build
        run: npm run build
